site_name: Aamir Hussain
site_description: Aamir Hussain's personal author page

site_url: https://aamiranauthor.ca

nav:
  - 'index.md'
  - 'book.md'
  - 'about.md'
  - 'happenings.md'
  - Blog:
    - blog/index.md
  - 'advocacy.md'
  - 'hobbies/hobbies.md'

theme:
  name: material
  custom_dir: overrides
  favicon: images/moon.svg
  icon:
    logo: fontawesome/regular/moon
  palette:
    # Palette toggle for book mode
    - scheme: underthefullandcrescentmooncolour
      toggle:
        icon: material/book-open-variant-outline
        name: Currently in book theme
    # Palette toggle for dark mode
    - scheme: aamiranauthorcolour
      toggle:
        icon: material/pen
        name: Currently in author theme
  features:
    - navigation.tabs
  font:
    text: Libre Franklin
    code: Playfair

extra_css:
  - stylesheets/extra.css 
  - stylesheets/stars.css

plugins:
  - privacy
  - search
  - social:
      cards_layout_options: 
        background_color: "#4d2e00"
        font_family: Playfair
       

  - blog:
      post_date_format: yyyy/MMM/d
      post_url_date_format: yyyy/MMM/d
      archive_date_format: yyyy-MMM
      archive_url_date_format: yyyy/MMM
      post_url_format: "{date}/{slug}"
      categories_allowed:
        - Writing
        - Book
        - Site Update
        - Advocacy
        - Palestine
        - TTRPG
        - Review
        - Life
        - Proportional Representation
        - Islam
        - Current Events
        - Movie
        - Canada

markdown_extensions:
  - footnotes
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra:
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, this is absolutely not required for any functionality and is completely optional.
  analytics:
    provider: google
    property: G-MHHH858QRH
  social:
    - icon: simple/linktree
      link: https://linktr.ee/aamirauthor
    - icon: simple/instagram
      link: https://www.instagram.com/aamiranauthor/
    - icon: simple/tiktok
      link: https://www.tiktok.com/@aamiranauthor
    - icon: simple/facebook
      link: https://www.facebook.com/AamirAnAuthor
    - icon: simple/mastodon
      link: https://mstdn.ca/@azih
    - icon: simple/threads
      link: https://www.threads.net/@aamiranauthor
    - icon: simple/bluesky
      link: https://bsky.app/profile/aamiranauthor.bsky.social
      


copyright: This website by <span property="cc:attributionName">Aamir Hussain</span> is licensed under <a href="http://creativecommons.org/licenses/by-nc-sa/4.0/?ref=chooser-v1" target="_blank" rel="license noopener noreferrer" style="display:inline-block;">CC BY-NC-SA 4.0 &copy; 2024-2025 - <a href="#__consent"> Change cookie settings</a> - <a href=/privacy> Privacy Policy</a>
        